### PR TITLE
ウェブサイトアドレス情報入力画面を日本仕様に

### PR DESCRIPTION
**Pull request by TimLai125**

### CODE REVIEW

**Comment by TimLai125** [comment]
@yostashiro Please review the module and let me know if you have any concerns,

For the templates that the module overwrites:

1. website_sale.address, https://github.com/odoo/odoo/blob/cae336478391f53b1d66644337da4152c8cbc14a/addons/website_sale/views/templates.xml#L1112-L1241

2. portal.portal_my_details, https://github.com/odoo/odoo/blob/cae336478391f53b1d66644337da4152c8cbc14a/addons/portal/views/portal_templates.xml#L225-L310

**Comment by yostashiro** [comment]
@TimLai125 I do not have specific concerns about overriding the templates except that I wish there was a better way than overriding the entire templates.  I guess the adjustment could be made easier if there were enough hook points embedded in the original template, but that is not the case at the moment.

What about the proposal of Japan as the default value for country field?

**Comment by TimLai125** [comment]
@yostashiro Since the default value of `country_id` in `res.partner` is defined with "Japan", the newly created(sign up) user on E-commerce side will have the default value upon registration, or you wish to embed the default value in `l10n_jp_address_layout` and make it be dependencies of this module?

**Comment by yostashiro** [comment]
@TimLai125 It would be nice to be able to set the default through configuration (Website > Settings) only for the frontend, without depending on the `ir.value` settings.  Would it be tricky to do so?

**Comment by TimLai125** [comment]
@yostashiro It should not be tricky to do so, I just found out there are some examples that we could follow to have a `ir.config_settings` field in website templates.

**Comment by yostashiro** [comment]
@TimLai125 Would you also be able to check if it's possible to propose the country based on GeoIP?  GeoIP didn't appear to be working when I checked with 10.0.  If we can make it work, I think that would be the best.

**Comment by TimLai125** [comment]
@yostashiro The module now will also support GeoIP, the priority of selecting the default country:
1. The res.partner setting
2. The website configuration
3. Country from GeoIP 

Please let me know if you have any other concerns. Otherwise, I will merge the PR.

**Comment by yostashiro** [comment]
@TimLai125 It sounds really cool.  Thanks!

**Pull request merged**
